spring.application.name=Sunil-Ornaments
server.port=8082


#Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=sunil_ornaments
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driverClassName=org.postgresql.Driver

#Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# # Spring security credentials
#spring.security.user.name=sudhir
#spring.security.user.password=sudhir@123